### PR TITLE
Fixed Arrow keys by pass panVertical/panHorizontal bug

### LINKED ISSUE #1630: Arrows keys bypass panHorizontal/panVertical = false
Even if panHorizontal/panVertical are set to false the user is still able to pan around using the arrows keys.

### PR DESCRIPTION
**Pull request by JachiOnuoha**
Fixes #1630

### CODE REVIEW

File: src/viewer.js [hunk 1]
```diff
@@ -2657,8 +2657,8 @@ function onCanvasKeyDown( event ) {
     var canvasKeyDownEventArgs = {
       originalEvent: event.originalEvent,
       preventDefaultAction: false,
-      preventVerticalPan: event.preventVerticalPan,
-      preventHorizontalPan: event.preventHorizontalPan
+      preventVerticalPan: !this.panVertical,
```
Comment (iangilman) [inline src/viewer.js:2660]: I don't know for sure if the passed-in `event.preventVerticalPan` is ever used, but just to be on the safe side, I think it would be better to just add the new logic, so this line would become:

`preventVerticalPan: event.preventVerticalPan && !this.panVertical,`

Same for the other three similar lines, of course.

File: test/demo/basic.html [hunk 2]
```diff
@@ -21,13 +21,12 @@
     <script type="text/javascript">
 
         var viewer = OpenSeadragon({
-            // debugMode: true,
+            debugMode: true,
```
Comment (iangilman) [inline test/demo/basic.html:24]: The basic.html file is definitely good for testing, but please return it to its original state before checking in. In this case, please comment this line back out again.

**Review by iangilman — CHANGES_REQUESTED** [review]
Thank you for tackling another feature here!

File: src/viewer.js (hunk 1 above)
Comment (JachiOnuoha) [reply src/viewer.js:2660]: I see your point. I did some debugging and discovered that `event.preventVerticalPan` and `event.preventHorizontalPan` always remain undefined and are never updated thus, causing the issue. From my understanding, wouldn't `preventVerticalPan: event.preventVerticalPan && !this.panVertical` always evaulate to undefined? I haven't tested to see if this is the outcome yet but I'm just curious

Comment (iangilman) [reply src/viewer.js:2660]: Right, it should be `event.preventVerticalPan || !this.panVertical`... sorry for getting that wrong! Even with `event.preventVerticalPan` being undefined that should work.

**Review by iangilman — APPROVED** [review]
OK, this looks great, thank you! I agree that perhaps the extra logic of including the `event.preventVerticalPan` is maybe unnecessary, but it still seems like the safest move.

Can you please remove the pull request's "draft" status so we can merge it?

We're going to be releasing 3.0 very soon (see https://github.com/openseadragon/openseadragon/issues/1985), and we're currently in a "no changes" mode, so I'm not going to merge this until afterwards. This is a very safe fix, but still we don't want any chance of destabilization.

**Comment by iangilman** [comment]
Merging, now that 3.0 has been released!
