### PR TITLE
[FIX #1188] added fix for supporting weird filenames that look like JSONs

### LINKED ISSUE #1188: Filenames with special characters interpreted as JSON?
I'm trying to open a file with the path:
`/fcgi-bin/iipsrv.fcgi?DeepZoom=/data/images/EXxx-xxxx-x-CKXXX-[Boon's]-AV.svs.dzi`

When I pass this in the `viewer.open()` function I get the following error:

```
osdCamicroscope.php?tissueId=test:1 Uncaught SyntaxError: Unexpected token / in JSON at position 0
    at Function.parse [as parseJSON] (<anonymous>)
    at Function.parseJSON (openseadragon.js:2264)
    at getTileSourceImplementation (openseadragon.js:8749)
    at $.Viewer.addTiledImage (openseadragon.js:8010)
    at doOne (openseadragon.js:7346)
    at $.Viewer.open (openseadragon.js:7351)
```

I think this is due to the match statement `tileSource.match( /\s*[\{\[].*/ )` [[Source]](https://github.com/openseadragon/openseadragon/blob/80611e999a2c88739e770994777acf6d555d8c05/src/viewer.js#L2130)

Which returns a matched JSON for the file location I'm using. Thus it tries to parse this file location as a JSON leading to the error.

### PR DESCRIPTION
**Pull request by lastlegion**
better check for JSON instead of regex.

### CODE REVIEW

File: src/viewer.js [hunk 1]
```diff
@@ -2127,7 +2141,7 @@ function getTileSourceImplementation( viewer, tileSource, imgOptions, successCal
         if ( tileSource.match( /^\s*<.*>\s*$/ ) ) {
             tileSource = $.parseXml( tileSource );
         //json should start with "{" or "[" and end with "}" or "]"
-        } else if ( tileSource.match(/^\s*[\{\[].*[\}\]]\s*$/ ) ) {
+        } else if ( _isJSON(tileSource) ) {
```
Comment (iangilman) [inline src/viewer.js]: I guess it's not a big deal, but it seems inefficient to parse the string twice. Maybe instead we should have a try/catch around a $.parseJSON (which we use instead of JSON.parse because we're still supporting IE8 (See https://github.com/openseadragon/openseadragon/issues/373)) here, and then test the result.

**Comment by lastlegion** [comment]
Thanks for the feedback. I've incorporated both the changes in: https://github.com/openseadragon/openseadragon/pull/1189/commits/ce1360f5cb65e4c194183c96c7ae1c2221604ba7

**Comment by lastlegion** [comment]
Accidentally closed it.

**Comment by iangilman** [comment]
Beautiful! Thank you for fixing this :)
