### PR TITLE
Fix zoomTo/zoomBy with ref point and immediately to true. Fix #800

### LINKED ISSUE #800: zoomTo/zoomBy ignore refPoint if immediately is true
The refPoint handling is done in `update` (where it's called zoomPoint): 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L908-L920

...but since `immediately` calls `reset` on the spring: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L777

...that part of update doesn't get exercised.

### PR DESCRIPTION
**Pull request by avandecreme**
I broke the tests. I am not sure what is going on yet.
Anyway the tests were checking for very odd zoom values (-1 and 0) which we should reject in the first place I think.

### CODE REVIEW

**Comment by avandecreme** [comment]
Ok, test fixed.
It turns out that setting `defaultZoomLevel` after opening the viewer does not work.
The tests were passing before because there was a special case for the first zoom level tested (-1).

File: src/viewport.js [hunk 1]
```diff
@@ -805,21 +805,24 @@ $.Viewport.prototype = {
...
         this.zoomPoint = refPoint instanceof $.Point &&
             !isNaN(refPoint.x) &&
             !isNaN(refPoint.y) ?
             refPoint :
             null;
 
-        if ( immediately ) {
-            this.zoomSpring.resetTo( zoom );
+        if (immediately) {
+            var _this = this;
```
Comment (iangilman) [inline src/viewport.js]: I think it's a good practice to put the `var _this` at the top of the function (unlike other variables where I prefer to keep them near where they're used) since in the future it might be needed elsewhere in the function.

**Comment by iangilman** [comment]
Awesome, thank you for taking this one on! Good to have the tests cleaned up like that as well. 

Just one super minor style point, if you want to fix that. Otherwise I think this is ready to land!

**Comment by iangilman** [comment]
@avandecreme Thanks again for fixing this!

**Comment by avandecreme** [comment]
Ha, you didn't give me enough time for the little fix :)

**Comment by iangilman** [comment]
Sorry... just got caught up in a bunch of OSD stuff I was doing :)
