### PR TITLE
Doc: small documentation fix

### LINKED ISSUE #2111: Doc: small documentation fix
This line should say `dblClickDistThreshold` - not `clickDistThreshold`:

https://github.com/openseadragon/openseadragon/blob/51e3ea7fa08f10765be25f4c1f9ba7764ee6e79b/src/mousetracker.js#L169

### PR DESCRIPTION
**Pull request by shyamkumaryadav**
Fixes https://github.com/openseadragon/openseadragon/issues/2111

> This line should say `dblClickDistThreshold` - not `clickDistThreshold`:
> 
> https://github.com/openseadragon/openseadragon/blob/51e3ea7fa08f10765be25f4c1f9ba7764ee6e79b/src/mousetracker.js#L169

### CODE REVIEW

File: src/mousetracker.js [hunk 1]
```diff
@@ -166,7 +166,7 @@
         /**
          * The maximum distance allowed between two pointer click events
          * to be treated as a click gesture.
```
Comment (iangilman) [inline src/mousetracker.js:168]: This line should also be changed so `click` is `double-click`.

**Review by iangilman — CHANGES_REQUESTED** [review]
Thank you for catching this! One minor addition...

File: src/mousetracker.js (hunk 1 above)
Comment (shyamkumaryadav) [reply src/mousetracker.js]: done

**Review by iangilman — APPROVED** [review]
Awesome, thank you!
