### PR TITLE
fix(a11y): draw the level based on pixel density ratio

### LINKED ISSUE #1763: a11y: browser zoom
Users with low vision may prefer to have their browser zoom into page content to make it easier to read. Openseadragon should select a tile with a resolution that is not blurry

#### Detailed Reproduction Steps:
1. Go to http://openseadragon.github.io/examples/developer-debug-mode/
2. Change browser zoom to 500%

### What is the expected behavior?
The image should be in a good resolution

### What is the current behavior?
The image is blurry

### PR DESCRIPTION
**Pull request by ronnymikalsen**
Users with low vision may prefer to have their browser zoom into page content to make it easier to read. Openseadragon should select a tile with a resolution that is not blurry

Fixes #1763

### CODE REVIEW

**Comment by ronnymikalsen** [comment]
I found out that $.pixelDensityRatio is only called once. If i redefine the function $.pixelDensityRatio , then it seems to works. But this is duplicate code, and that is bad. I will try to figure out a better solution

File: src/tiledimage.js [hunk 1]
```diff
@@ -1018,7 +1018,7 @@ $.extend($.TiledImage.prototype, $.EventSource.prototype, /** @lends OpenSeadrag
         );
         var currentZeroRatio = this.viewport.deltaPixelsFromPointsNoRotate(
             this.source.getPixelRatio(0), true).x *
-            this._scaleSpring.current.value;
+            this._scaleSpring.current.value * $.pixelDensityRatio;
```
Comment (iangilman) [inline src/tiledimage.js:1021]: Can you explain why this addition is needed? Likewise with the other change in this file. I can see how it might be good, but it's interesting that we didn't already have it here. I'm curious what you found that led you to it.

File: src/viewer.js [hunk 2]
```diff
@@ -426,6 +426,9 @@ $.Viewer = function( options ) {
         }
     }
 
+    // Add updatePixelDensityRatio to resize event
+    $.addEvent( window, 'resize', this.updatePixelDensityRatio.bind(this) );
```
Comment (iangilman) [inline src/viewer.js:430]: We'll need a corresponding `$.removeEvent` in the `destroy` function to properly clean up.

File: src/viewer.js [hunk 3]
```diff
@@ -1608,6 +1611,20 @@ $.extend( $.Viewer.prototype, $.EventSource.prototype, $.ControlDock.prototype,
         return this.world.removeItem(drawer);
     },
 
+    /**
+     * Update pixel density ration, clears all tiles and triggers updates for
```
Comment (iangilman) [inline src/viewer.js:1615]: This comment should mention the fact that it only clears the tiles if the ratio has changed. Also, you've got a typo: `ration`.

File: src/viewer.js [hunk 4]
```diff
@@ -1608,6 +1611,20 @@ $.extend( $.Viewer.prototype, $.EventSource.prototype, $.ControlDock.prototype,
...
+     * all items.
+     */
+    updatePixelDensityRatio: function() {
```
Comment (iangilman) [inline src/viewer.js:1618]: I don't think we need to add this to our public API. The style we're using to denote private functions these days is to add an `_` prefix to the function name. Also add `@private` to the doc comment.

**Review by iangilman — CHANGES_REQUESTED** [review]
Slick solution! Just a few notes...

File: src/tiledimage.js (hunk 1 above)
Comment (ronnymikalsen) [reply src/tiledimage.js]: `this.source.getPixelRatio` also need to take the pixel density into concern. I have refactored the changes in this file and moved them to `tilesource.getPixelRatio´. I think that is the correct place to do the calculations.

File: src/viewer.js (hunk 2 above)
Comment (ronnymikalsen) [reply src/viewer.js]: I agree. I had to refactor a little to make it work.

File: src/viewer.js (hunk 3 above)
Comment (ronnymikalsen) [reply src/viewer.js]: Thanks. I have fixed it.

File: src/viewer.js (hunk 4 above)
Comment (ronnymikalsen) [reply src/viewer.js]: I agree. I have fixed it.

**Review by iangilman — APPROVED** [review]
Fantastic! Looks great. Thank you for doing this :-)

I shall merge soon.
