### PR TITLE
Workaround for WebKit Pointer Event Implicit Capture Bug

### LINKED ISSUE #1962: WebKit Pointer Event Implicit Capture Bug
## Applies To

Pointer events, touch devices, on WebKit-based browsers.

## Issue

Scenario: A parent and a child element, both with pointerdown event handlers. Depending on application's need, when a pointerdown occurs on the child, it should be ignored and the parent (when pointer down bubbles) will want to capture the pointer:

1. pointerdown on child
1. child calls hasPointerCapture and determines pointer is captured implicitly (touch)
1. child immediately calls releasePointerCapture
1. pointerdown bubbles to parent
1. Parent calls setPointerCapture
1. Parent processes pointermove events until pointerup, pointercancel, or lostpointercapture

Per the specification (quoted below), implicitly captured pointers can be released at the target element's pointerdown event handler. This can be used to give a parent element a chance to capture the pointer.

On WebKit user-agents, when the sequence of operations above are followed, capture isn't really released for the pointer at the child element. When the parent calls setPointerCapture() for its element, a gotpointercapture event is fired indicating capture was successful, but the parent element doesn't actually have the pointer captured - pointermove and pointerup events won't be fired at the element with capture if the touch contact point moves off the element ([which by definition is what pointer capture is for](https://w3c.github.io/pointerevents/#pointer-capture)). This makes it impossible to reliably track pointers for gestures like click, drag, pinch, etc.

So far, on all other browsers tested there's been no issues. Only WebKit-based browsers exhibit the issue. Links below to bug filed with WebKit.

## Specification

(from [Implicit Pointer Capture in the W3C Pointer Events Spec](https://w3c.github.io/pointerevents/#implicit-pointer-capture))

**_Direct manipulation devices should behave exactly as if setPointerCapture was called on the target element just before the invocation of any pointerdown listeners. The hasPointerCapture API may be used (eg. within any pointerdown listener) to determine whether this has occurred. If releasePointerCapture is not called for the pointer before the next pointer event is fired, then a gotpointercapture event will be dispatched to the target (as normal) indicating that capture is active._**

## [Test Page](https://openseadragon-imaging.github.io/old-demo/test.html)

The grey box is the parent, green box is child (from the original issue description above)

If the pointerdown is initiated on the child (green box) in a Webkit browser, the parent (grey box) doesn't truly get capture despite the gotpointercapture event indicating it does...this is shown by the inability to drag the parent if pointer moves outside of the container (black) element (and perhaps worst of all, if pointerup outside of container it's never dispatched to the parent).

## Links:

[WebKit Bugzilla bug report](https://bugs.webkit.org/show_bug.cgi?id=220196)
[Pointer Events Working Group discussion](https://github.com/w3c/pointerevents/issues/327)
[Test Page](https://openseadragon-imaging.github.io/old-demo/test.html)
[OpenSeadragon example page, broken on WebKit](https://openseadragon-imaging.github.io/#/mousetracker)
[W3C Pointer Events Specification](https://w3c.github.io/pointerevents/)
[W3C Touch Events Specification](https://www.w3.org/TR/touch-events/)

### PR DESCRIPTION
**Pull request by msalsbery**
Fixes #1962

Also improved event handling on legacy touch/mouse devices

### The Problem and the Fix
In the pointer event model, touch (and other "direct manipulation devices") get [pointer capture](https://w3c.github.io/pointerevents/#pointer-capture) implicitly when a user makes a contact with the device. If a child element doesn't require pointer capture, capture can be released in a pointerdown event handler. When the event bubbles to a parent element, that parent can request pointer capture. The WebKit bug (described in #1962) prevents a parent element from capturing pointers on pointerdown events. The implicit capture at the child isn't released as requested, or held - not sure where subsequent events go at that point. When the parent requests capture it should get all subsequent pointermove and pointerup events targeted at its element's event handlers. On WebKit this doesn't happen, so if the user drags the pointer outside the parent element it stops receiving pointermove events, and more importantly won't receive the pointerup event indicating termination of a gesture. This leaves MouseTrackers pointer tracking in an unstable state, thinking there's still pointer contact.

To fix, on pointerdown events for touch, MouseTracker now checks to see if preventDefault() has already been called for the event (by a child element, which would indicate the child is handling a gesture) and if not, then lets the child keep its implicit capture on the pointer but flags itself as having capture and proceeds with gesture handling on bubbled pointermove and pointerup events as if it has pointer capture. This matches the way legacy touch events work, where pointer capture is ALWAYS given to the target element with no way of relinquishing capture so a parent element can take capture, so it's a reasonable approach and seems to work well - on both pointer events and legacy touch events!

### Demo Sites
[OpenSeadragon Imaging ImagingHelper Demo](https://openseadragon-imaging.github.io/#/imaginghelper)
[OpenSeadragon Imaging MouseTracker Demo](https://openseadragon-imaging.github.io/#/mousetracker)
[Legacy OpenSeadragon Imaging ImagingHelper Demo](https://openseadragon-imaging.github.io/old-demo/index.html)
[CodePen](https://codepen.io/msalsbery/pen/dyOeXqO)

### Preview Builds
[openseadragon.js](https://openseadragon-imaging.github.io/old-demo/lib/openseadragon.js)
[openseadragon.js.map](https://openseadragon-imaging.github.io/old-demo/lib/openseadragon.js.map)
[openseadragon.min.js](https://openseadragon-imaging.github.io/old-demo/lib/openseadragon.min.js)
[openseadragon.min.js.map](https://openseadragon-imaging.github.io/old-demo/lib/openseadragon.min.js.map)

### CODE REVIEW

**Comment by msalsbery** [comment]
@iangilman This was a not so fun one ;-)  Ready for review

File: src/openseadragon.js [hunk 1]
```diff
@@ -1911,14 +1911,15 @@ function OpenSeadragon( options ){
...
 
         /**
-         * Sets the specified element's pointer-events style attribute to 'none'.
+         * Sets the specified element's pointer-events style attribute to the passed value.
          * @function
          * @param {Element|String} element
+         * @param {String} value
          */
-        setElementPointerEventsNone: function( element ) {
+        setElementPointerEvents: function( element, value ) {
```
Comment (iangilman) [inline src/openseadragon.js:1919]: I imagine this isn't used a lot outside of OSD, but technically it is not private, so maybe it's worth keeping a `setElementPointerEventsNone` that calls this new one, just so we don't risk breaking someone who's using it.

**Review by iangilman — CHANGES_REQUESTED** [review]
Awesome! 

I don't see any Safari-specific code, which is great. Still, I'm curious how this fixes the Webkit-specific issue. Could you add a couple notes to the PR about what it's doing, so I understand and for posterity?

File: src/openseadragon.js (hunk 1 above)
Comment (msalsbery) [reply src/openseadragon.js:1919]: Oh yeah, thanks! I had it that way and then, thinking I could cut down on code bloat, I removed it :-/  Will fix!

File: src/mousetracker.js [hunk 2]
```diff
@@ -2570,12 +2574,12 @@
         if ( eventInfo.stopPropagation ) {
             $.stopEvent( event );
         }
-        if ( eventInfo.shouldCapture && !implicitlyCaptured ) {
-           //$.console.log('pointerdown calling capturePointer() ' + (tracker.userData ? tracker.userData.toString() : '') + ' ' + (event.target === tracker.element ? 'tracker.element' : ''));
-           capturePointer( tracker, gPoint );
-        } else if ( !eventInfo.shouldCapture && implicitlyCaptured ) {
-           //$.console.log('pointerdown calling releasePointer() ' + (tracker.userData ? tracker.userData.toString() : '') + ' ' + (event.target === tracker.element ? 'tracker.element' : ''));
-           releasePointer( tracker, gPoint ); //TODO should we do this? Investigate when implementing bubble handling
```
Comment (msalsbery) [inline src/mousetracker.js:2578]: @iangilman  Here's the main bit that fixes the issue, as described in the text I added to this PR's description

**Comment by msalsbery** [comment]
> Awesome!
> 
> I don't see any Safari-specific code, which is great. Still, I'm curious how this fixes the Webkit-specific issue. Could you add a couple notes to the PR about what it's doing, so I understand and for posterity?

@iangilman I've added a note at the lines of code that provides the main fix..as well as a description of the issue and the fix in this PR's description

File: src/mousetracker.js [hunk 3]
```diff
@@ -2570,12 +2574,12 @@
...
+        if ( eventInfo.shouldCapture ) {
```
Comment (msalsbery) [inline src/mousetracker.js:2577]: @iangilman  Here's the main bit that fixes the issue, as described in the text I added to this PR's description

File: src/mousetracker.js [hunk 4]
```diff
@@ -2651,9 +2655,12 @@
         // Per spec, pointerup events are supposed to release capture. Not all browser
         //   versions have adhered to the spec, and there's no harm in releasing
         //   explicitly
-        if ( eventInfo.shouldReleaseCapture && event.target === tracker.element ) {
-           //$.stopEvent( event );
-           releasePointer( tracker, gPoint );
```
Comment (msalsbery) [inline src/mousetracker.js:2656]: @iangilman  ...and here's where it's undone on the pointerup event

File: src/openseadragon.js (hunk 1 above)
Comment (msalsbery) [reply src/openseadragon.js:1919]: @iangilman Fixed!

**Review by iangilman — APPROVED** [review]
Awesome... thank you for the clear explanation!

**Comment by msalsbery** [comment]
FYI, and note to self:

05/16/2022 it was [announced](https://bugs.webkit.org/show_bug.cgi?id=220196) that this Webkit bug was fixed and "shipped in Safari 15.5"

This should allow for some painful MouseTracker workaround code to be refactored out 😅

**Comment by iangilman** [comment]
@msalsbery Exciting! :)
